import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {api,norm} from './catalog-network.mjs';
const require=createRequire(import.meta.url),sharp=require(require.resolve('sharp',{paths:[process.cwd(),'C:/Users/Lucas/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules']}));
const id='burial-untrue',release='https://musicbrainz.org/release/e08c3db9-fc33-4d4e-b8b7-818d34228bef';
await mkdir('dist/assets/hq',{recursive:true});await mkdir('dist/assets/backs',{recursive:true});
const caa=await api(release.replace('musicbrainz.org','coverartarchive.org')+'/');
const d=await api('https://api.deezer.com/search/album?q=artist:%22Burial%22%20album:%22Untrue%22');
const match=d.data.find(x=>norm(x.title)==='untrue'&&norm(x.artist.name)==='burial');
const officialTracks=[['Untitled',46],['Archangel',238],['Near Dark',234],['Ghost Hardware',293],['Endorphin',177],['Etched Headplate',359],['In McDonalds',127],['Untrue',376],['Shell of Light',280],['Dog Shelter',179],['Homeless',320],['UK',100],['Raver',299]];
const album=match?await api('https://api.deezer.com/album/'+match.id):{tracks:{data:officialTracks.map(([title,duration])=>({title,duration,link:'https://burial.bandcamp.com/album/untrue'}))}};
const apple=(await api('https://itunes.apple.com/search?term=Burial%20Untrue&entity=album&limit=10'))?.results?.find(x=>norm(x.collectionName)==='untrue'&&norm(x.artistName)==='burial');
const a={id,title:'Untrue',artist:'Burial',release:'2007-11-05',releaseVerified:true,listened:2026,genre:'Dubstep / UK garage',type:'Álbum',score:10,label:'Hyperdub',url:'https://burial.bandcamp.com/album/untrue',listenLabel:'Ouvir no Bandcamp',source:'Hyperdub / MusicBrainz',sources:[{name:'Hyperdub / Bandcamp',url:'https://burial.bandcamp.com/album/untrue'},{name:'MusicBrainz',url:release},{name:'Deezer',url:album.link}],review:['A cidade continua tocando depois que a festa acaba.','Em Untrue, as vozes parecem chegar de outra sala: cortadas, distantes, às vezes quase desfeitas. As batidas quebradas dão movimento a essa névoa, enquanto o baixo sustenta uma sensação de peso que nunca precisa ocupar todo o espaço. Archangel e Near Dark fazem a melancolia caminhar; os interlúdios deixam a paisagem respirar.','O que mais impressiona nesta leitura demonstrativa é a proximidade que nasce desses fragmentos. Ghost Hardware tem uma pulsação inquieta, Etched Headplate mistura vulnerabilidade e impulso, e Raver encerra o percurso sem fechar completamente a porta. Um disco para ouvir inteiro, percebendo como o silêncio e a textura costuram uma faixa à próxima.'],catalogDescription:'Segundo álbum de Burial, lançado pela Hyperdub em 2007. A edição em CD reúne 13 faixas.',tracks:album.tracks.data.map((t,i)=>({name:t.title,number:i+1,duration:t.duration*1000,url:t.link}))};
for(const side of ['front','back']){
 const candidates=caa.images.filter(i=>i[side]&&i.approved).map(i=>i.image.replace('http:','https:'));if(side==='front'&&album.cover_xl)candidates.push(album.cover_xl);
 if(side==='front'&&apple?.artworkUrl100)candidates.push(apple.artworkUrl100.replace('100x100bb','3000x3000bb'));
 let best;for(const url of candidates){try{const r=await fetch(url,{signal:AbortSignal.timeout(45000)});if(!r.ok)continue;const buffer=Buffer.from(await r.arrayBuffer());if(buffer.length>30e6)continue;const meta=await sharp(buffer,{limitInputPixels:50e6}).metadata();if(!best||Math.min(meta.width,meta.height)>Math.min(best.meta.width,best.meta.height))best={buffer,meta,url};}catch(e){console.log(side,e.message);}}
 if(!best)throw Error('Missing '+side);const base=(side==='front'?'assets/hq/':'assets/backs/')+id,ext=best.meta.format==='png'?'png':'jpg';await writeFile('dist/'+base+'-original.'+ext,best.buffer);
 if(side==='front'){a.coverOriginal=base+'-original.'+ext;a.coverWidth=best.meta.width;a.coverHeight=best.meta.height;a.coverSource=best.url.includes('coverartarchive')?'Cover Art Archive':best.url.includes('mzstatic.com')?'Apple / iTunes':'Deezer';a.coverSourceUrl=best.url;a.coverVariants=[];for(const width of [480,960,1800].filter(w=>w<best.meta.width).concat(Math.min(1800,best.meta.width))){const p=base+'-'+width+'.webp';if(a.coverVariants.some(v=>v.width===width))continue;await sharp(best.buffer).resize({width,withoutEnlargement:true}).webp({quality:94}).toFile('dist/'+p);a.coverVariants.push({src:p,width});}a.cover=a.coverVariants.at(-1).src;const color=await sharp(best.buffer).resize(1,1).removeAlpha().raw().toBuffer();a.color='#'+[...color].slice(0,3).map(n=>n.toString(16).padStart(2,'0')).join('');}
 else{a.backCoverOriginal=base+'-original.'+ext;a.backCover=base+'.webp';a.backCoverWidth=best.meta.width;a.backCoverHeight=best.meta.height;a.backCoverSource={name:'Cover Art Archive',url:best.url,release};await sharp(best.buffer).rotate().resize({width:1400,height:1400,fit:'inside',withoutEnlargement:true}).webp({quality:95}).toFile('dist/'+a.backCover);}
 console.log(side,best.meta.width,best.meta.height,best.url);
}
a.sources=a.sources.filter(s=>s.url);const producer={name:'Burial',role:'Produção',source:{name:'MusicBrainz',url:release}};a.credits=[producer];a.tracks.forEach(t=>t.credits=[producer]);
const catalogue=JSON.parse(await readFile('dist/catalog.json','utf8'));const previous=catalogue.find(x=>x.id===id);if(previous)Object.assign(a,{review:previous.review,score:previous.score});catalogue.splice(0,0,...(!previous?[a]:[]));if(previous)catalogue[catalogue.indexOf(previous)]=a;
await writeFile('dist/catalog.json.tmp',JSON.stringify(catalogue,null,2)+'\n');await rename('dist/catalog.json.tmp','dist/catalog.json');console.log('Untrue added',a.tracks.length);
